esphome:
  name: esp32-jk-bms-only
  friendly_name: D1电池

external_components:
  - source: github://syssi/esphome-jk-bms@main
    components: [jk_bms_ble]

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

logger:
  level: INFO

api:

ota:
  platform: esphome
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 110ms

ble_client:
  mac_address: "98:DA:20:0D:37:D0"
  id: ble_d1

jk_bms_ble:
  ble_client_id: ble_d1
  id: bms_d1
  protocol_version: JK02_32S
  throttle: 5s

switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms_d1
    charging:
      name: "D1_SW1 充电开关"
    discharging:
      name: "D1_SW2 放电开关"
    balancer:
      name: "D1_SW3 均衡开关"

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms_d1
    balancing:
      name: "D1_BAL 均衡中"
    charging:
      name: "D1_ST_CHG 充电状态"
    discharging:
      name: "D1_ST_DIS 放电状态"
    online_status:
      name: "D1_ON BMS在线状态"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms_d1
    total_voltage:
      name: "D1_S01 总电压"
    current:
      name: "D1_S02 充放电电流"
    power:
      name: "D1_S03 实时功率"
    charging_power:
      name: "D1_P_CHG 充电功率"
    discharging_power:
      name: "D1_P_DIS 放电功率"
    heating_current:
      name: "D1_I_HEAT 加热电流"
    state_of_charge:
      name: "D1_S04 SOC电量"
    capacity_remaining:
      name: "D1_S05 剩余容量"
    full_charge_capacity:
      name: "D1_CAP_FULL 额定总容量"
    total_charging_cycle_capacity:
      name: "D1_S06 总循环容量AH"
    average_cell_voltage:
      name: "D1_S07 平均单串电压"
    min_cell_voltage:
      name: "D1_S08 单串最低电压"
    max_cell_voltage:
      name: "D1_S09 单串最高电压"
    delta_cell_voltage:
      name: "D1_S10 电芯压差"
    cell_voltage_1:
      name: "D1_CELL01 第1串电压"
    cell_voltage_2:
      name: "D1_CELL02 第2串电压"
    cell_voltage_3:
      name: "D1_CELL03 第3串电压"
    cell_voltage_4:
      name: "D1_CELL04 第4串电压"
    cell_voltage_5:
      name: "D1_CELL05 第5串电压"
    cell_voltage_6:
      name: "D1_CELL06 第6串电压"
    cell_voltage_7:
      name: "D1_CELL07 第7串电压"
    cell_voltage_8:
      name: "D1_CELL08 第8串电压"
    cell_voltage_9:
      name: "D1_CELL09 第9串电压"
    cell_voltage_10:
      name: "D1_CELL10 第10串电压"
    cell_voltage_11:
      name: "D1_CELL11 第11串电压"
    cell_voltage_12:
      name: "D1_CELL12 第12串电压"
    cell_voltage_13:
      name: "D1_CELL13 第13串电压"
    cell_voltage_14:
      name: "D1_CELL14 第14串电压"
    cell_voltage_15:
      name: "D1_CELL15 第15串电压"
    cell_voltage_16:
      name: "D1_CELL16 第16串电压"
    cell_voltage_17:
      name: "D1_CELL17 第17串电压"
    cell_resistance_1:
      name: "D1_R01 1#电芯内阻"
    cell_resistance_2:
      name: "D1_R02 2#电芯内阻"
    cell_resistance_3:
      name: "D1_R03 3#电芯内阻"
    cell_resistance_4:
      name: "D1_R04 4#电芯内阻"
    cell_resistance_5:
      name: "D1_R05 5#电芯内阻"
    cell_resistance_6:
      name: "D1_R06 6#电芯内阻"
    cell_resistance_7:
      name: "D1_R07 7#电芯内阻"
    cell_resistance_8:
      name: "D1_R08 8#电芯内阻"
    cell_resistance_9:
      name: "D1_R09 9#电芯内阻"
    cell_resistance_10:
      name: "D1_R10 10#电芯内阻"
    cell_resistance_11:
      name: "D1_R11 11#电芯内阻"
    cell_resistance_12:
      name: "D1_R12 12#电芯内阻"
    cell_resistance_13:
      name: "D1_R13 13#电芯内阻"
    cell_resistance_14:
      name: "D1_R14 14#电芯内阻"
    cell_resistance_15:
      name: "D1_R15 15#电芯内阻"
    cell_resistance_16:
      name: "D1_R16 16#电芯内阻"
    cell_resistance_17:
      name: "D1_R17 17#电芯内阻"
    mosfet_temperature:
      name: "D1_S11 MOS管温度"
    temperature_sensor_1:
      name: "D1_S12 温度探头1"
    temperature_sensor_2:
      name: "D1_S13 温度探头2"

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms_d1
    total_runtime_formatted:
      name: "D1_T01 累计运行时长"
    errors:
      name: "D1_T02 BMS故障日志"
    operation_mode:
      name: "D1_MODE 运行模式"
    battery_type:
      name: "D1_BATT_TYPE 电池类型"

#不需要状态灯直接删除下面两行
status_led:
  pin: GPIO2
