esphome:
  name: esp32-t35
  friendly_name: ESP32 T35蓝牙桥接

esp32:
  board: esp32dev
  # 可选：切换IDF框架，按需开启
  # framework:
  #   type: esp-idf

# WiFi联网
wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD

# 修复OTA缺少platform报错，添加平台声明
ota:
  platform: esp32
  password: !secret OTA_PASSWORD

# 原生HA直连，移除加密，不再需要API_KEY
api:

# 蓝牙代理扫描T35广播
bluetooth_proxy:
  active: true

# T35温湿度电量解析
sensor:
  - platform: xiaomi_ble
    mac_address: BC:A8:44:24:06:D7
    bindkey: !secret T35_KEY
    temperature:
      name: "T35 温度"
      state_class: measurement
      unit_of_measurement: "°C"
    humidity:
      name: "T35 湿度"
      state_class: measurement
      unit_of_measurement: "%"
    battery_level:
      name: "T35 设备电量"
      unit_of_measurement: "%"
