name: Build ESPHome Firmware
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yaml_file:
          - esp32-t35.yaml
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 生成secrets.yaml密钥文件
        run: |
          cat > secrets.yaml << EOF
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
          WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
          OTA_PASSWORD: ${{ secrets.OTA_PASSWORD }}
          T35_KEY: ${{ secrets.T35_KEY }}
          EOF

      - name: ESPHome云端编译固件
        uses: esphome/build-action@v7.1.0
        with:
          yaml-file: ${{ matrix.yaml_file }}
          version: stable

      - name: 打印编译目录（调试用，可删除）
        run: ls -laR ./.esphome/build

      - name: 上传固件bin文件
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.yaml_file }}-bin
          path: ./.esphome/build/**/*.bin
          if-no-files-found: ignore
          include-hidden-files: true
